In [1]:
import numpy as np 

In [2]:
arrego_np = np.array([1,2,3])

In [3]:
type(arrego_np)

numpy.ndarray

In [4]:
np.zeros((1))

array([0.])

In [5]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.zeros((5,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
np.ones((1))

array([1.])

In [10]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
np.empty((3))

array([0., 0., 0.])

In [12]:
np.empty((3,2,2))

array([[[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,              nan]],

       [[-3.10503618e+231, -4.33579095e-311],
        [-3.10503618e+231, -1.73059941e-077]]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(3,10)
# [3,10[


array([3, 4, 5, 6, 7, 8, 9])

In [26]:
arreglo_pares=np.arange(0,20,2)
# [3 ,10[ #2  

In [23]:
arreglo_pares.size

10

In [27]:
arreglo_pares.shape

(10,)

In [28]:
arreglo_pares.reshape((5,2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [31]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [32]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [33]:
a= np.array([10,10,10])
b= np.array((5,5,5))

In [34]:
b

array([5, 5, 5])

In [35]:
a-b

array([5, 5, 5])

In [36]:
a/b

array([2., 2., 2.])

In [37]:
a+b

array([15, 15, 15])

In [38]:
a%2

array([0, 0, 0])

In [39]:
arreglo_doce =np.arange(12)

In [40]:
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
arreglo_doce > 12 


array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [42]:
arreglo_doce >3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [45]:
A = np.arange(4).reshape((2,2))

In [46]:
A

array([[0, 1],
       [2, 3]])

In [48]:
B=np.arange(4,8).reshape((2,2))

In [49]:
A * B

array([[ 0,  5],
       [12, 21]])

In [50]:
a+b

array([15, 15, 15])

In [51]:
a / b

array([2., 2., 2.])

In [52]:
a % b

array([0, 0, 0])

In [54]:
arreglo_tres = np.arange(3)
arreglo_tres +=2

In [55]:
arreglo_tres.sum()

9

In [56]:
arreglo_tres.max()

4

In [59]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)

In [60]:
arreglo_tres_cuatro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
arreglo_tres_cuatro.sum(axis=0)

array([12, 15, 18, 21])

In [64]:
arreglo_tres_cuatro.sum(axis =1)

array([ 6, 22, 38])